//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caregiver
    {
        public int CaregiverID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SocialSecurity { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> HouseNum { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
    }
}
